/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package da.application.form.other;

import da.component.EventItem;
import da.model.SanPham;
import da.service.SanPhamService;
import java.awt.BorderLayout;
//import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTargetAdapter;
import org.jdesktop.animation.timing.interpolation.PropertySetter;
import raven.toast.Notifications;

/**
 *
 * @author ADMIN
 */
public class FprmSanPham extends javax.swing.JPanel {
private FormHome home;
    private Animator animator;
    //private SanPham itemSelected;
    private SanPhamService sanPhamService;

    /**
     * Creates new form FprmSanPham
     */
    public FprmSanPham() {
        initComponents();
        sanPhamService = new SanPhamService(); // Khởi tạo sanPhamService
        init();
        
        animator = new Animator(500);
        animator.addTarget(new PropertySetter(mainPanel1, "imageSize", new Dimension(180, 120), mainPanel1.getTargetSize()));
        animator.addTarget(new TimingTargetAdapter() {
            @Override
            public void end() {
                mainPanel1.setImageOld(null);
            }
        });
        animator.setResolution(0);
        animator.setAcceleration(.5f);
        animator.setDeceleration(.5f);  
    }
    
    private void init() {
        home = new FormHome();
        mainPanel1.setLayout(new BorderLayout());
        mainPanel1.add(home);
        loadData(sanPhamService.getAll()); // Load initial data
    }

    private void loadData(ArrayList<SanPham> danhSachSanPham) {
        home.clearItems(); // Clear existing items
//        home.setEvent(new EventItem() {
//            @Override
//            public void itemClick(Component com, SanPham item) {
//                if (itemSelected != null) {
//                    mainPanel1.setImageOld(new ImageIcon(itemSelected.getHinhanh()));
//                }
//                if (itemSelected != item) {
//                    if (!animator.isRunning()) {
//                        itemSelected = item;
//                        mainPanel1.setImage(new ImageIcon(item.getHinhanh()));
//                        mainPanel1.setImageSize(new Dimension(180, 120));
//                        mainPanel1.repaint();
//                        home.setSelected(com);
//                        animator.start();
//                    }
//                }
//            }
//        });
        for (SanPham sp : danhSachSanPham) {
            home.addItem(sp);
        }
    }
    
    public void refreshSanPham() {
        ArrayList<SanPham> danhSachSanPham = sanPhamService.getAll();
        loadData(danhSachSanPham);
        Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Đã làm mới danh sách sản phẩm!");
    }
    
    public void search() {
        String keyword = txtSearch.getText().trim();
        loadData(sanPhamService.searchSanPham(keyword));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new da.component.MainPanel();
        crazyPanel18 = new raven.crazypanel.CrazyPanel();
        txtSearch = new javax.swing.JTextField();
        cmdSearch = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1173, 657));

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1161, Short.MAX_VALUE)
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        crazyPanel18.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "background:$Table.background",
            new String[]{
                "JTextField.placeholderText=Search;background:@background"
            }
        ));
        crazyPanel18.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "",
            "[]push[][]",
            "",
            new String[]{
                "width 200"
            }
        ));

        txtSearch.setPreferredSize(new java.awt.Dimension(90, 22));
        crazyPanel18.add(txtSearch);

        cmdSearch.setText("Search");
        cmdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSearchActionPerformed(evt);
            }
        });
        crazyPanel18.add(cmdSearch);

        jButton7.setText("Refesh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        crazyPanel18.add(jButton7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(crazyPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(crazyPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        refreshSanPham();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cmdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSearchActionPerformed
        search();
    }//GEN-LAST:event_cmdSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdSearch;
    private raven.crazypanel.CrazyPanel crazyPanel18;
    private javax.swing.JButton jButton7;
    private da.component.MainPanel mainPanel1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
